version: '3'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '8080:8080'
    environment:
      MONGODB_URL: "mongodb://mongo:27017/ssi-api"
      ACCOUNT_ADDRESS: ""
      ACCOUNT_PRIVATE_ENCRYPTION_KEY: ""
      ACCOUNT_PRIVATE_KEY: ""
      ACCOUNT_PUBLIC_ENCRYPTION_KEY: ""
